# Generated by Django 5.2.6 on 2025-09-17 23:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 639-1 (2 letras).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2,5}$', "Use código ISO 639-1, p. ej. 'es'.")])),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 4217 (3 letras).', max_length=3, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{3}$', "Use código ISO 4217, p. ej. 'CLP'.")])),
                ('nombre', models.CharField(max_length=30)),
                ('simbolo', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código ISO 3166-1 alpha-2 (2 letras).', max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z]{2}$', "Use código ISO 3166-1 alpha-2, p. ej. 'CL'.")])),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LibroFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(db_index=True, max_length=16, unique=True)),
                ('ean', models.CharField(blank=True, max_length=16, null=True)),
                ('titulo', models.CharField(db_index=True, max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('autor', models.CharField(db_index=True, max_length=100)),
                ('autor_prologo', models.CharField(blank=True, max_length=40, null=True)),
                ('traductor', models.CharField(blank=True, max_length=40, null=True)),
                ('ilustrador', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_paginas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('alto_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grosor_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_gr', models.PositiveIntegerField(blank=True, null=True)),
                ('numero_edicion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_edicion', models.DateField(db_index=True)),
                ('numero_impresion', models.PositiveIntegerField(blank=True, null=True)),
                ('tematica', models.CharField(blank=True, max_length=60, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento_distribuidor', models.DecimalField(decimal_places=1, help_text='Porcentaje de 0.0 a 99.9', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99.9)])),
                ('resumen_libro', models.TextField()),
                ('codigo_imagen', models.CharField(blank=True, max_length=120, null=True)),
                ('rango_etario', models.CharField(blank=True, max_length=30, null=True)),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='roles.editorial')),
                ('idioma_original', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.idioma')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.moneda')),
                ('pais_edicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.pais')),
                ('tipo_tapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipotapa')),
            ],
            options={
                'ordering': ['titulo'],
                'indexes': [models.Index(fields=['isbn'], name='catalogo_li_isbn_e23631_idx'), models.Index(fields=['titulo'], name='catalogo_li_titulo_5d8407_idx'), models.Index(fields=['autor'], name='catalogo_li_autor_5bbf04_idx'), models.Index(fields=['fecha_edicion'], name='catalogo_li_fecha_e_6f1ae4_idx'), models.Index(fields=['editorial'], name='catalogo_li_editori_3f16c2_idx')],
            },
        ),
    ]
