# Generated by Django 5.2.6 on 2025-09-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroficha',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='autor_prologo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='codigo_imagen',
            field=models.CharField(default='sin_imagen', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='descuento_distribuidor',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='ean',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='grosor_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='idioma_original',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='ilustrador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='moneda',
            field=models.CharField(default='CLP', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='numero_edicion',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='numero_impresion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='numero_paginas',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='pais_edicion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='peso_gr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='rango_etario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='resumen_libro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='tematica',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='libroficha',
            name='tipo_tapa',
            field=models.CharField(default='Tapa blanda', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libroficha',
            name='traductor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='autor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='libroficha',
            name='fecha_edicion',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
