# Generated by Django 5.2.6 on 2025-09-26 19:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('TC', 'Tipo de cambio')], max_length=10)),
                ('nombre_tipo', models.CharField(blank=True, help_text='Ej: USD, EUR, IVA', max_length=10, null=True)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogo.moneda')),
            ],
            options={
                'ordering': ['tipo', 'moneda'],
                'indexes': [models.Index(fields=['tipo', 'moneda'], name='catalogo_va_tipo_b95403_idx'), models.Index(fields=['nombre_tipo'], name='catalogo_va_nombre__b3acf9_idx')],
                'unique_together': {('tipo', 'moneda')},
            },
        ),
    ]
