# Generated by Django 5.2.6 on 2025-09-30 22:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('id_fiscal', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo_origen', models.DecimalField(decimal_places=2, default=0, help_text='Cargo origen (% sobre el costo del libro)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('recargo_fletes', models.DecimalField(decimal_places=2, default=0, help_text='Recargo fletes y gastos (% sobre el costo)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gastos_indirectos', models.DecimalField(decimal_places=2, default=0, help_text='Gastos indirectos (% sobre el costo)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('margen_comercializacion', models.DecimalField(decimal_places=2, default=0, help_text='Margen de comercialización (% sobre el costo)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Si está deshabilitada no se puede editar')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EDITOR', 'Editor'), ('CONSULTOR', 'Consultor'), ('ADMIN', 'Admin')], default='CONSULTOR', max_length=20)),
                ('must_change_password', models.BooleanField(db_index=True, default=False, help_text='Si está en True, debe cambiar la contraseña al iniciar sesión.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='UsuarioEditorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.editorial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de editorial',
                'verbose_name_plural': 'Usuarios de editorial',
                'constraints': [models.UniqueConstraint(fields=('user', 'editorial'), name='unique_usuario_editorial')],
            },
        ),
    ]
