# Generated by Django 5.2.6 on 2025-09-27 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='cargo_origen',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cargo origen (% sobre el costo del libro)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='editorial',
            name='gastos_indirectos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Gastos indirectos (% sobre el costo)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='editorial',
            name='margen_comercializacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Margen de comercialización (% sobre el costo)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='editorial',
            name='recargo_fletes',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recargo fletes y gastos (% sobre el costo)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
