# Generated by Django 5.1 on 2025-09-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_editorial_cargo_origen_editorial_gastos_indirectos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Si está deshabilitada no se puede editar'),
        ),
    ]
